name: sincotdashboard
description: "Dashboard."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  supabase_flutter: ^2.8.3
  shared_preferences: ^2.3.5
  permission_handler: ^11.3.1
  file_picker: ^8.1.7
  url_launcher: ^6.3.1
  archive: ^4.0.2
  xml: ^6.5.0
  path_provider: ^2.1.5
  logging: ^1.3.0
  flutter_downloader: ^1.12.0
  intl: ^0.20.2




dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/